### ISSUE TITLE
Quests available for new Horde Druids.

### ISSUE THREAD

**Issue by uutfboomheadshot** [uutfboomheadshot/AcherusWoW#11]
Remove the following.

"A Lesson to Learn"
"Moonglade"
"Torwa Pathfinder"

**Comment by Nassahi92** [comment]
Tested on local and remote server and it works fine.

**Comment by uutfboomheadshot** [comment]
Still showing a quest for horde now. "Lessons Anew"  Alliance is fine.
![wowscrnshot_110115_000124](https://cloud.githubusercontent.com/assets/7526918/10866559/c809ee7a-802b-11e5-87c5-398d52242e1b.jpg)

**Comment by Nassahi92** [comment]
Removed and tested and OK. Will close.
