### ISSUE TITLE
Warlock Starting Quests

### ISSUE THREAD

**Issue by uutfboomheadshot** [uutfboomheadshot/AcherusWoW#13]
2 quests available from the horde warlock trainer: 
"In search of menara voidrender" 
"an imp's request"

3 Available from the Alliance warlock trainer:
"In search of menara voidrender" 
"knowledge of the orb of orahill" 
"an imp's request"

![wowscrnshot_110115_145943](https://cloud.githubusercontent.com/assets/7526918/10869492/a0a70e2a-80a9-11e5-9c71-55eb0dbfac35.jpg)
![wowscrnshot_110115_150301](https://cloud.githubusercontent.com/assets/7526918/10869493/a8c9e03c-80a9-11e5-8761-9601a824878b.jpg)

**Comment by Nassahi92** [comment]
Quests removed, have tested on live and local servers and all OK. will close.
