### ISSUE TITLE
Quest Removal Shamans

### ISSUE THREAD

**Issue by uutfboomheadshot** [uutfboomheadshot/AcherusWoW#16]
Showing for horde characters:

"Material Assistance"
"Elemental Mastery"
"Relic of the Earthern Ring"

![wowscrnshot_110115_162556](https://cloud.githubusercontent.com/assets/7526918/10869922/7b7a09ca-80b5-11e5-98b4-5b0c01ef45b0.jpg)

Showing for Alliance

"Elemental Mastery"
"Call of Water"
"Call of Air"
"Relic of the Earthern Ring"

![wowscrnshot_110115_162727](https://cloud.githubusercontent.com/assets/7526918/10869931/907f795e-80b5-11e5-9bb1-6193a7afd9b9.jpg)

**Comment by Nassahi92** [comment]
Tested on local and remote and works fine.
