### ISSUE TITLE
Remove NPC "Grimwing" from Acherus Ebon Hold

### ISSUE THREAD

**Issue by uutfboomheadshot** [uutfboomheadshot/AcherusWoW#18]
Grimwing is a flightmaster, don't want players exiting Acherus to go to the "old" world.

Database GUID : 125825

![wowscrnshot_110115_175136](https://cloud.githubusercontent.com/assets/7526918/10870375/55162c8a-80c1-11e5-98fa-3256dc96d7ee.jpg)

**Comment by Nassahi92** [comment]
Tested on local and remote and works fine.
