### ISSUE TITLE
Fix Hearthstone / starting location for classes / races 

### ISSUE THREAD

**Issue by Nassahi92** [uutfboomheadshot/AcherusWoW#5]
Code:
 1 - Human
2 - Orc
3 - Dwarf
4 - Nightelf
5 - Undead
6 - Tauren
7 - Gnome
8 - Troll
10 - Bloodelf
11 - Draenei
Code:
1 - Warrior
2 - Paladin
3 - Hunter
4 - Rogue
5 - Priest
7 - Shaman
8 - Mage
9 - Warlock
11 - Druid

**Comment by uutfboomheadshot** [comment]
Missing DK Class ID in that list
